project_id = "mupqzdkhwrmmtsnktunw"

[functions.fetch-stock-prices]
verify_jwt = false

[functions.fetch-stock-history]
verify_jwt = false

[functions.fetch-mf-nav]
verify_jwt = false

[functions.fetch-market-indices]
verify_jwt = false

[functions.stock-assistant]
verify_jwt = false
